import test from 'node:test';
import assert from 'node:assert/strict';
import {freshState,recordAnswer,startBattle,combatTurn,finishBattle,maxHealth,maxFocus,baseDamage} from '../engine.mjs';
import {career,grantGrowth,openChest,equipItem,upgradeEquipment,combineEquipment,trainTalent,gearStats,awardItem,restartCareer,SLOTS,itemStats} from '../progression.mjs';
const add=(s,key,n)=>{for(let i=0;i<n;i++)s=awardItem(s,key);return s;};
test('male and female characters have equal combat stats and serialize correctly',()=>{const a=freshState('A','','mixed','male'),b=freshState('B','','mixed','female');assert.equal(maxHealth(a),maxHealth(b));assert.equal(baseDamage(a,'strike'),baseDamage(b,'strike'));assert.equal(JSON.parse(JSON.stringify(b)).character,'female');});
test('XP carries over multiple levels, awards points once, and survives save serialization',()=>{let s=grantGrowth(freshState(),200,3,2);assert.equal(career(s).level,3);assert.equal(career(s).xp,25);assert.equal(career(s).points,2);assert.equal(career(s).chests,3);assert.deepEqual(career(JSON.parse(JSON.stringify(s))),career(s));s=trainTalent(s,'might');assert.equal(baseDamage(s,'strike'),20);assert.equal(career(s).points,1);assert.throws(()=>trainTalent(s,'unknown'));});
test('chest consumes one token and preserves selected set and slot; repeated opening fails',()=>{let s=openChest(freshState(),'chest','sentinel',()=>.5);assert.equal(career(s).chests,0);assert.equal(career(s).inventory['chest:sentinel:0'],1);assert.throws(()=>openChest(s,'sword','dawn'));assert.throws(()=>openChest(freshState(),'bogus','dawn'));s=openChest(freshState(),'helmet','sage',()=>.1);assert.equal(career(s).inventory['helmet:sage:1'],1);});
test('equipping and upgrading changes actual attack and spends exact resources',()=>{let s=add(freshState(),'sword:dawn:0',1);s=equipItem(s,'sword:dawn:0');s.coins=50;s=grantGrowth(s,0,2);assert.equal(baseDamage(s,'strike'),19);s=upgradeEquipment(s,'sword');assert.equal(baseDamage(s,'strike'),20);assert.equal(s.coins,25);assert.equal(career(s).ore,1);assert.equal(career(s).slotLevels.sword,2);assert.throws(()=>upgradeEquipment(s,'chest'));});
test('merging consumes exactly three matching items, upgrades equipped gear and retains slot level',()=>{let s=add(freshState(),'sword:dawn:0',3);s=add(s,'sword:sage:0',2);s=equipItem(s,'sword:dawn:0');s.career.slotLevels.sword=4;s=combineEquipment(s,'sword:dawn:0');assert.equal(career(s).inventory['sword:dawn:0'],undefined);assert.equal(career(s).inventory['sword:dawn:1'],1);assert.equal(career(s).inventory['sword:sage:0'],2);assert.equal(career(s).equipped.sword,'sword:dawn:1');assert.equal(career(s).slotLevels.sword,4);assert.throws(()=>combineEquipment(s,'sword:dawn:1'));});
test('rarity upgrades enforce level cap and prevent merging beyond Mythic',()=>{let s=add(freshState(),'sword:dawn:0',3);s=equipItem(s,'sword:dawn:0');s.coins=1000;s.career.ore=100;s.career.slotLevels.sword=5;assert.throws(()=>upgradeEquipment(s,'sword'));s=combineEquipment(s,'sword:dawn:0');s=upgradeEquipment(s,'sword');assert.equal(s.career.slotLevels.sword,6);s=add(s,'sword:dawn:4',3);assert.throws(()=>combineEquipment(s,'sword:dawn:4'));});
test('battle rewards grant XP and a chest once and never alter Bible scores',()=>{let s=startBattle(freshState());while(!s.battle.done)s=combatTurn(s,s.focus?'radiance':'strike',()=>.9);s=finishBattle(s);assert.equal(career(s).xp,25);assert.equal(career(s).chests,2);assert.equal(s.attempts.length,0);assert.throws(()=>finishBattle(s));});
test('three correct Bible trials grant XP, forge resources and a chest; retries cannot double reward',()=>{let s=freshState();for(let i=0;i<3;i++){s.pending={id:'q'+i,answer:'Jesus',prompt:'Who?',reference:'John 1:1',mode:'quiz'};s.feedback=null;s=recordAnswer(s,'Jesus');}assert.equal(career(s).level,2);assert.equal(career(s).xp,15);assert.equal(career(s).ore,6);assert.equal(career(s).chests,2);assert.throws(()=>recordAnswer(s,'Jesus'));});
test('three and six piece sets affect combat, defense, regeneration and focus',()=>{for(const set of ['dawn','sentinel','sage']){let s=freshState();for(const slot of SLOTS){s=add(s,`${slot.id}:${set}:0`,1);s=equipItem(s,`${slot.id}:${set}:0`);}const g=gearStats(s);assert.equal(g.sets[set],6);if(set==='dawn'){assert.equal(g.burn,4);let b=combatTurn(startBattle(s),'strike',()=>.9);assert.equal(b.battle.burn,4);}if(set==='sentinel'){assert.equal(g.regen,3);assert.equal(g.defense,7);}if(set==='sage'){assert.equal(maxFocus(s),4);assert.equal(g.focusRegen,1);}}});
test('equipment and talents cannot change during combat, and unowned items cannot be equipped',()=>{let s=add(freshState(),'sword:dawn:0',3);s=grantGrowth(s,100,5);s.coins=100;s=startBattle(s);assert.throws(()=>equipItem(s,'sword:dawn:0'));assert.throws(()=>combineEquipment(s,'sword:dawn:0'));assert.throws(()=>trainTalent(s,'might'));assert.throws(()=>openChest(s,'sword','dawn'));assert.throws(()=>equipItem(freshState(),'sword:dawn:4'));});
test('new quests keep career and gold, reset temporary skills and score, and increase enemy strength',()=>{let s=grantGrowth(freshState('Hero','','mixed','female'),200,6,2);s=add(s,'helmet:dawn:1',1);s=equipItem(s,'helmet:dawn:1');s.coins=75;s.skills={vigor:3};s.attempts=[{correct:true}];const next=restartCareer(s,freshState(s.name,s.alias,s.mode,s.character));assert.equal(next.character,'female');assert.equal(next.coins,75);assert.equal(next.career.level,3);assert.equal(next.career.runs,1);assert.equal(next.health,maxHealth(next));assert.deepEqual(next.skills,{});assert.equal(next.attempts.length,0);assert.ok(startBattle(next).battle.max>startBattle(s).battle.max);});

test('every rarity and level upgrade improves each item’s primary stat',()=>{for(const slot of SLOTS){const stat=slot.attack?'attack':slot.hp?'hp':'defense';for(let rarity=0;rarity<4;rarity++){const key=slot.id+':dawn:'+rarity;assert.ok(itemStats(slot.id+':dawn:'+(rarity+1))[stat]>itemStats(key)[stat]);assert.ok(itemStats(key,2)[stat]>itemStats(key,1)[stat]);}}});
