import test from 'node:test';
import assert from 'node:assert/strict';
import {newProfile,startRun,runChoice,planMove,arrive,runBattle as prepareBattle,beginBattle,runCombat,finishRunBattle,settleRun,returnToLobby,trainWithGold,enterShop,buyRunOffer,runAnswer,migrate,campChoice} from '../run.mjs';
import {baseDamage,drawSkillChoices,freshState} from '../engine.mjs';
import {equipItem,awardItem,fusionRecipe,fuseEquipment,protectEquipment,resetEquipmentLevel,upgradeEquipment} from '../progression.mjs';
const runBattle=(s,kind)=>beginBattle(prepareBattle(s,kind,()=>0));
const active=()=>{let s=startRun(newProfile('Test'));s.skillChoices=['frost'];return runChoice(s,'frost');};
test('new and migrated profiles start in lobby without erasing permanent resources or results',()=>{const old={...freshState('Old'),coins:70,stage:3,armor:[0,1],attempts:[{correct:false,reference:'John 1:1'}]};const s=migrate(old);assert.equal(s.phase,'lobby');assert.equal(s.coins,70);assert.equal(s.unlocked,3);assert.equal(s.attempts.length,1);assert.equal(newProfile().phase,'lobby');});
test('saved movement resumes without consuming a second turn or reroll',()=>{const s=planMove(active(),()=>.8);const restored=JSON.parse(JSON.stringify(s));assert.deepEqual(planMove(restored,()=>0),s);const done=arrive(restored);assert.equal(done.run.turn,1);assert.equal(done.position,10);assert.equal(done.run.move,null);});
test('finite board forces scripture, shops, elites, and final boss',()=>{let s=active();const found=[];for(let i=0;i<30;i++){s=arrive(planMove({...s,event:null},()=>0));found.push(s.event);}assert.equal(found[2],'trial');assert.equal(found[4],'market');assert.equal(found[9],'elite');assert.equal(found[19],'elite');assert.equal(found[29],'boss');});
test('defeat settles once, leaves zero health, preserves missed verses and awards permanent gold',()=>{let s=runBattle(active());s.health=1;s.battle.hp=9999;s.battle.max=9999;s.battle.turn=1;s.path='wayfarer';s.run.turn=4;s.attempts=[{correct:false,reference:'John 2:1'}];s=runCombat(s,'strike',()=>.99);assert.equal(s.health,0);assert.equal(s.battle.outcome,'lost');s=finishRunBattle(s);assert.equal(s.phase,'results');assert.equal(s.coins,20);assert.equal(s.health,0);assert.equal(s.history[0].attempts[0].reference,'John 2:1');assert.deepEqual(settleRun(s,'defeat'),s);assert.throws(()=>finishRunBattle(s));});
test('victory needs a defeated boss, unlocks chapter, pays once, and awards learning armor once',()=>{let s=active();assert.throws(()=>settleRun(s,'victory'));s.run.turn=30;s.stageCorrect=4;s=runBattle(s,'boss');s.battle.hp=1;s=runCombat(s,'strike',()=>.99);s=finishRunBattle(s);assert.equal(s.unlocked,1);assert.ok(s.armor.includes(0));assert.equal(s.phase,'results');assert.equal(s.history.length,1);const gold=s.coins;s=settleRun(s,'victory');assert.equal(s.coins,gold);});
test('gold training improves the next run and old temporary skills/tokens reset',()=>{let s=active();s.run.turn=10;s.skills={fire:2};s.tokens=99;s=returnToLobby(settleRun(s,'retired'));const before=baseDamage(s,'strike');s=trainWithGold(s,'might');assert.equal(baseDamage(s,'strike'),before+2);s=startRun(s);assert.deepEqual(s.skills,{});assert.equal(s.tokens,0);assert.equal(s.run.turn,0);assert.throws(()=>trainWithGold(s,'might'));assert.throws(()=>equipItem(s,'sword:dawn:0'));});
test('run shop consumes tokens only, sold-out offers cannot repeat, and stat boosts affect combat',()=>{let s=enterShop({...active(),tokens:100,coins:70});const damage=baseDamage(s,'strike');s=buyRunOffer(s,1);assert.equal(s.tokens,70);assert.equal(s.coins,70);assert.equal(baseDamage(s,'strike'),damage+4);assert.throws(()=>buyRunOffer(s,1));});
test('Bible rewards defer permanent level and chest payouts until run settlement',()=>{let s=active();s.pending={answer:'Jesus',mode:'quiz',id:'q',reference:'John 1:1'};s=runAnswer(s,'Jesus');assert.equal(s.career.xp,0);assert.equal(s.run.xp,30);assert.equal(s.coins,0);assert.equal(s.tokens,10);assert.throws(()=>runAnswer(s,'Jesus'));});
test('conditional skills are absent before prerequisites and offered after their build investment',()=>{const s=active();for(let i=0;i<20;i++)assert.ok(!drawSkillChoices(s,()=>i/20).includes('meteor'));const built={...s,skills:{fire:2}};let seen=false;for(let i=0;i<100;i++)seen ||= drawSkillChoices(built,()=>i/100).includes('meteor');assert.ok(seen);});
test('Epic fusion uses base same-slot fodder, preserves unrelated equipped/protected pieces, and keeps slot level',()=>{let s=newProfile();for(const key of ['sword:dawn:2','sword:sentinel:2','sword:sage:2'])s=awardItem(s,key);s=equipItem(s,'sword:sentinel:2');s=protectEquipment(s,'sword:sage:2');assert.equal(fusionRecipe(s,'sword:dawn:2').ready,false);s=awardItem(s,'sword:sentinel:2');s.career.slotLevels.sword=8;const recipe=fusionRecipe(s,'sword:dawn:2');assert.equal(recipe.key,'sword:dawn:2:1');s=fuseEquipment(s,'sword:dawn:2');assert.equal(s.career.inventory['sword:sentinel:2'],1);assert.equal(s.career.equipped.sword,'sword:sentinel:2');assert.equal(s.career.inventory['sword:sage:2'],1);assert.equal(s.career.slotLevels.sword,8);});
test('level reset refunds exact paid investment once without destroying gear',()=>{let s=awardItem({...newProfile(),coins:100},'sword:dawn:0');s.career.ore=20;s=equipItem(s,'sword:dawn:0');s=upgradeEquipment(s,'sword');s=upgradeEquipment(s,'sword');s=resetEquipmentLevel(s,'sword');assert.equal(s.coins,100);assert.equal(s.career.ore,20);assert.equal(s.career.inventory['sword:dawn:0'],1);assert.deepEqual(resetEquipmentLevel(s,'sword'),s);});
test('Guardian shielding cannot turn an overwhelming fatal hit into a free revival',()=>{let s=runBattle(active(),'boss');s.health=1;s.run.turn=30;s.battle.hp=9999;s.battle.turn=3;s.battle.intent='heavy';s.skills={};s=runCombat(s,'strike',()=>.99);assert.equal(s.health,0);assert.equal(s.battle.outcome,'lost');});
test('Last Light rescues one fatal hit and the second fatal hit ends the attempt',()=>{let s=runBattle(active(),'boss');s.path='wayfarer';s.skills={revive:1};s.health=1;s.run.turn=30;s.battle.hp=9999;s.battle.intent='heavy';s=runCombat(s,'strike',()=>.99);assert.ok(s.health>0);assert.equal(s.run.revived,true);assert.equal(s.battle.done,false);assert.equal(s.battlesLost,0);s.health=1;s=runCombat(s,'strike',()=>.99);assert.equal(s.battle.outcome,'lost');assert.equal(finishRunBattle(s).phase,'results');});
test('Lightweaver milestone damage resolves before the enemy counterattack',()=>{let s=active();s.path='arcanist';s.career.level=5;s=runBattle(s);s.skills={};s.battle.hp=39;s.health=1;s.run.charge=100;s=runCombat(s,'radiance',()=>.99);assert.equal(s.battle.outcome,'won');assert.ok(s.health>0);});
test('advanced rarity breakthrough requires exact upgraded duplicates',()=>{let s=newProfile();s=awardItem(s,'sword:dawn:2:2');s=awardItem(s,'sword:sage:2:2');s=awardItem(s,'sword:sentinel:2:2');assert.equal(fusionRecipe(s,'sword:dawn:2:2').ready,false);s=awardItem(s,'sword:dawn:2:2');s=awardItem(s,'sword:dawn:2:2');s=fuseEquipment(s,'sword:dawn:2:2');assert.equal(s.career.inventory['sword:dawn:3'],1);assert.equal(s.career.inventory['sword:sage:2:2'],1);});
test('ultimate charge gates the attack, builds during combat, and resets on use',()=>{let s=runBattle(active());s.run.charge=0;s.battle.hp=9999;assert.throws(()=>runCombat(s,'radiance'));s=runCombat(s,'strike',()=>.99);assert.ok(s.run.charge>0);s.run.charge=100;s=runCombat(s,'radiance',()=>.99);assert.equal(s.run.charge,0);});
test('equipped weapons change ultimate burn, shields and lightning/refund behavior',()=>{for(const set of ['dawn','sentinel','sage']){let profile=awardItem(newProfile(),'sword:'+set+':2');profile=equipItem(profile,'sword:'+set+':2');let s=startRun(profile);s=runChoice(s,s.skillChoices[0]);s.skills={};s.path='wayfarer';s=runBattle(s);s.run.charge=100;s.battle.hp=9999;s=runCombat(s,'radiance',()=>.99);if(set==='dawn')assert.equal(s.battle.burn,8);if(set==='sentinel')assert.ok(s.battle.shield>0);if(set==='sage'){assert.equal(s.run.charge,20);assert.ok(s.battle.effects.includes('Starfall'));}}});


test('camp training trades healing for temporary attack; rest heals and charges the ultimate',()=>{
 const s={...active(),event:'camp',health:40,skills:{}};s.run.charge=20;
 const trained=campChoice(s,'train');assert.equal(trained.health,40);assert.equal(baseDamage(trained,'strike'),baseDamage(s,'strike')+3);assert.equal(trained.event,null);
 const rested=campChoice(s,'rest');assert.ok(rested.health>40);assert.equal(rested.run.charge,45);assert.equal(rested.run.stats.attack,s.run.stats.attack);assert.throws(()=>campChoice(rested,'train'));
});
test('enemy shield blocks damage and regeneration responds to burn',()=>{
 let s=runBattle(active());s.skills={};s.battle.variant=1;s.battle.enemyShield=12;s.battle.hp=999;s.battle.max=999;
 const shielded=runCombat(s,'strike',()=>.99);assert.equal(shielded.battle.enemyShield,0);assert.equal(999-shielded.battle.hp,baseDamage(s,'strike')-12);
 s.battle.variant=0;s.battle.enemyShield=0;s.battle.turn=4;
 assert.ok(runCombat(s,'strike',()=>.99).battle.effects.includes('Enemy regenerates 6'));
 s.battle.burn=4;assert.ok(runCombat(s,'strike',()=>.99).battle.effects.includes('Enemy regenerates 3'));
});
test('settlement archives the run build and removes temporary stats from the lobby',()=>{
 let s=active();s.skills={heart:2,fire:2};s.run.stats.attack=9;s=settleRun(s,'retired');assert.deepEqual(s.skills,{});assert.deepEqual(s.history[0].build,{heart:2,fire:2});assert.equal(s.tokens,0);
});

test('camp training offers learned skills only and never grants a free new skill',()=>{let s={...active(),event:'camp',skills:{fire:1,poison:2,frost:3}};s=campChoice(s,'train',()=>0);assert.deepEqual(s.skillChoices,['fire','poison']);assert.equal(s.upgradePending,true);s=runChoice(s,'fire');assert.equal(s.skills.fire,2);assert.equal(s.skills.poison,2);});

test('encounters wait for explicit Start Battle and preserve waiting through reload',()=>{const s=prepareBattle(active());assert.equal(s.battle.started,false);assert.throws(()=>runCombat(s,'strike'),/Start Battle/);const loaded=JSON.parse(JSON.stringify(s));assert.equal(loaded.battle.turn,1);const started=beginBattle(loaded);assert.equal(started.battle.started,true);assert.ok(runCombat(started,'strike',()=>.99).battle.turn>1);});
